FROM python:3.10

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY requirements.txt /usr/src/app/requirements.txt
RUN /usr/local/bin/python -m pip install --no-cache-dir -r /usr/src/app/requirements.txt

COPY ./src/ /usr/src/app/

CMD [ "/usr/local/bin/python", "/usr/src/app/src/msa.py" ]
