FROM alpine:3.16
RUN apk add --no-cache wget bash
RUN apk add build-base

RUN mkdir /software
WORKDIR /software
RUN wget http://msa.sbc.su.se/downloads/kalign/current.tar.gz -O ./kalign.tar.gz && tar -xf ./kalign.tar.gz && ./configure && make
RUN chmod -R 777 /software

ENTRYPOINT ["/software/kalign"]