FROM rust:latest

RUN mkdir -p /software
WORKDIR /software

RUN git clone https://github.com/robinhundt/bali-score.git
WORKDIR /software/bali-score
RUN cargo install --path .

CMD ["/software/bali-score"]